remote_theme: "mmistakes/minimal-mistakes"

title: irem
name: irem
description: small thoughts, in progress

# Enable features
plugins:
  - jekyll-include-cache

# Author (for sidebar later)
author:
  name: irem

# Basic layout
minimal_mistakes_skin: "dark"  # try "air", "dark", "neon", etc.

# Show excerpts on homepage
excerpt_separator: "<!--more-->"
